- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    email: blabla@truc.fr

  tasks:

  - name: RENDER THE F2BAN CONFIGURATION
    template:
      src: fban.j2
      dest: "f2ban.conf"
      mode: 0644
